name: aws_s3
on: push
jobs:
  action-1:
    runs-on: ubuntu-latest
    steps:
      - name: upload to s3
        uses: actions/checkout@v4
      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{vars.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key-id: ${{secrets.AWS_SECRET_ACCESS_KEY_ID}}
          aws-region: ap-south-1
